refactor(react-query): refactor fetch logic to use React Query
Taloreff-hls/WeatherApp pull request #2
Opened 2024-08-26 11:16 UTC by Taloreff-hls

### React Query
refactored the weather data fetching logic to use React Query instead of Axios, improving data management and performance. The update includes replacing manual state management with `useQuery` hooks and using React Query's built-in error handling and caching.

### MUI List
Added styles and components to MUI List such as "Box".

### Interface
Changed redundant WeatherData to IWeatherData

2024-08-26 11:37 UTC, DinFrid requested changes

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/BasicList.tsx
> +interface SearchesListProps {
interfaces convention: ISearchesListProps

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/BasicList.tsx
> +export default function SearchesList({searches} : SearchesListProps) {
```suggestion
const SearchesList: React.FC<SearchesListProps> = ({searches}) => {
```

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/BasicList.tsx
> +export default function SearchesList({searches} : SearchesListProps) {
change all function components to this syntax

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/CurrentWeather.tsx
> +export function CurrentWeather({ location, current }: IWeatherData) {
change to the syntax i mentioned before

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/LocationWeather.tsx
> +export function LocationWeather({ location, current }: IWeatherData) {
function component syntax

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/RecentSearches.tsx
>  interface RecentSearchesProps {
interface convention

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/RecentSearches.tsx
> +// import { ListItemText } from '@mui/material';
remove comments

2024-08-26 11:37 UTC, DinFrid commented on src/cmps/RecentSearches.tsx
> +                </List> */}
remove comments

2024-08-26 11:41 UTC, Taloreff-hls commented on src/cmps/BasicList.tsx
> +export default function SearchesList({searches} : SearchesListProps) {
Can you explain this decision? i understood this method is old fashioned

2024-08-27 06:56 UTC, ronc1812 requested changes

2024-08-27 06:56 UTC, ronc1812 commented on src/cmps/CurrentWeather.tsx
the CurrentWeather component and the LocationWeather have a lot of similar logic try to use component

2025-05-20 06:57 UTC, merged